### ISSUE TITLE
elf translation is not happening the same as “dfuse-pack.py”

### ISSUE THREAD

**Issue by amfern** [majbthrd/elf2dfuse#5]
> Thanks @amfern!  I appreciate your patience; I've merged the PR.  I would like to understand why the elf translation is not happening the same as “dfuse-pack.py”.  Is there a sample .elf that you could make publicly available?
_Originally posted by @majbthrd in https://github.com/majbthrd/elf2dfuse/pull/4#issuecomment-607874083_

This is inav firmware for kakutef7. https://send.firefox.com/download/f62a69897404eaaf/#l2c5pBj-T1PUkbwjzwHq7g

I am able to flash dfuse file produced by `pack-dfuse.py`, but the controller won't boot if i flash dfuse file produced by elf2dfuse.

There are two differences between the files, `dfu-from-hex.bin` has 2 elements, `dfu-from-elf.bin` has 3

The hex file was produced with `./tools/gcc-arm-none-eabi-8-2018-q4-major/bin/arm-none-eabi-objcopy -O ihex --set-start 0x08000000 obj/main/inav_KAKUTEF7.elf obj/inav_2.4.0_KAKUTEF7.hex`

**Comment by amfern** [comment]
```
dfu-from-elf.bin
(dfu-tool:3582982): FuPluginDfu-DEBUG: 20:44:17.121: DFU: DfuFirmware:
Vid:                     0x483
Pid:                     0xdf11
Release:                 0xffff
Version:                 0x100
  DfuImage:
  Elements:              3
== ELEMENT 0 ==
address:     0x8000000
contents:    0x01c8
== ELEMENT 1 ==
address:     0x80001d0
contents:    0x0114
== ELEMENT 2 ==
address:     0x8010000
contents:    0x52e0f


dfu-from-hex.bin
(dfu-tool:3583072): FuPluginDfu-DEBUG: 20:45:03.626: DFU: DfuFirmware:
Vid:                     0x483
Pid:                     0xdf11
Release:                 0x0
Version:                 0x100
  DfuImage:
  Name:                  ST...
  Elements:              2
== ELEMENT 0 ==
address:     0x8000000
contents:    0x02e4
== ELEMENT 1 ==
address:     0x8010000
contents:    0x52e0f

```

also there is some diff in the content, which seems related to the element header, but i am not sure.

```
~/Documents/iNavFlight/inav/obj master ❯ cmp -l dfu-from-elf.bin dfu-from-hex.bin | gawk '{printf "%08X %02X %02X\n", $1, strtonum(0$2), strtonum(0$3)}'                                                    20:28:49
00000013 00 01
00000017 00 53
00000018 00 54
00000019 00 2E
0000001A 00 2E
0000001B 00 2E
0000011A 03 02
00000122 C8 E4
00000123 01 02
000002EE D0 7C
000002EF 01 B6
000002F0 00 04
000002F1 08 00
000002F2 14 01
000002F3 01 00
00053221 FF 00
00053222 FF 00
0005322D 0D B5
0005322E 6E 58
0005322F 12 ED
00053230 2A E8
```

**Comment by majbthrd** [comment]
OK, as seen in the elf2dfuse.c code, the ELF file consists of lots of separate memory segments, and elf2dfuse (and/or the utility that you use to create a .bin out of the .elf) must de-fragment and arrange these.

dfuse-pack.py has much less work to do than elf2dfuse.c, as the elf to bin conversion has already done the task of decoding the ELF.  ELF files are a rather complicated file format.

We can ignore the differences from 0x13 to 0x1B.  These are merely the optional target name in the DfuSe header.

The difference at 0x11A is the number of elements (2 vs 3).

0x11D through 0x125 is the DfuSe 'Image Element' prefix.  The elf2dfuse file’s element is 0x1c8 bytes and the elf2bin+dfuse-pack.py element is 0x2e4 bytes; you can see those values.

elf2dfuse interpreted the ELF to have an eight byte hole between 0x800001c8 and 0x800001d0.

Sure enough, there is disparity (six bytes) starting at 0x2EE, which is where you would expect it (11 byte header + 274 byte header + 8 byte header + 0x1c8 byte element).

Beyond this, we shouldn’t expect sync (since one file has two elements and one has three... due to the hole).

So, the issues are:

1) What about this particular ELF file is causing a perceived hole between 0x1c8 and 0x1d0?
2) If there is a hole, what software is being used to convert the elf to X?  How is the software filling in the hole?  What is X (bin, ihex, ?)?
3) If there is not a hole, what is elf2dfuse misinterpreting?
4) If there is a hole, how is dfu-tool and the STM32 bootloader handling it?  (e.g. what gets written there?)
5) If there is a hole, does the target care about what is written in the hole?

Anyone wanting to debug this would need:
a) an ELF file that causes the trouble
b) a method of reproducing the ELF to X and then using dfuse-pack.py to go from X to DFU
c) time to figure out what is wrong

It may well have nothing to do with dfuse-pack.py and instead be the ELF to X conversion step.  Or, it could be how the target reacts to the values in the hole.

**Comment by majbthrd** [comment]
Also, you may get mileage out of using dfuse-pack.py to "dump" the contents of each .dfu file.

dfuse-pack.py has a "-d" option, and it outputs a series of ".dfu.targetX.imageX.bin" files as well as outputting to stdout where each of these binaries is located in memory.

This should make possible to verify:
i) whether or the two .dfu files are outputting the same binary data outside of the eight byte hole between 0x800001c8 and 0x800001d0
ii) what X + dfuse-pack.py is storing in the eight byte hole between 0x800001c8 and 0x800001d0

**Comment by majbthrd** [comment]
@amfern, sorry, I only just realized that you edited your earlier post to include a download link.

I'm sure there is a more optimal approach, but here is what I did after during a dfuse-pack.py -d for each of the DFU files:

```
$ dd if=/dev/zero of=hole.bin bs=8 count=1
$ rm -f join.bin
$ cat dfu-from-elf.bin.target0.image0.bin >> join.bin
$ cat hole.bin >> join.bin 
$ cat dfu-from-elf.bin.target0.image1.bin >> join.bin
```

and then a comparison reveals:

```
$ cmp -l dfu-from-hex.bin.target0.image0.bin join.bin 

457 174   0
458 266   0
459   4   0
461   1   0
```

So, it is binary identical except for the eight byte hole that elf2dfuse is incorrectly detecting.

**Comment by amfern** [comment]
@majbthrd Thanks you for looking into it, i wasn't aware pf  `dfuse-pack.py -d`, its good to know.
I am still puzzled as to why the flashing succeeds with dfu-util but not with dfu-tool.
Tbh i am also using them differently, with `dfu-util` i have to specify `alt` parameter, which is `0`, while with dfu-tool i don't need to specify the alt(rather specifying alt broken) but flashing the image without the gap works fine with.

I was trying to check in the code for 8 byte to not consider it as a gap so the first two blobs will get combined into one. But i broke it even more, does it sounds reasonable to you?
is there a way to use obj copy as a library maybe, so it can handle the parsing of elf format?

**Comment by majbthrd** [comment]
I have an impending code change that results in the same dfuse-pack.py -d result.  It should be uploaded in a few minutes, and I'll post an explanation.

**Comment by majbthrd** [comment]
@amfern, please try the latest commit.  The missing "hole" was a section with a sh_type of 0x70000001.

From what I can find online, values 0x70000001 through 0x7FFFFFFF "are reserved for processor-specific semantics".  For whatever reason, those eight-bytes were specially marked by the compiler; since the type wasn't known to elf2dfuse, it didn't include it in the result.

```
$ cmp -l new.dfu reference.dfu | gawk '{printf "%08X %02X %02X\n", $1, strtonum(0$2), strtonum(0$3)}'
00000013 00 01
00000017 00 53
00000018 00 54
00000019 00 2E
0000001A 00 2E
0000001B 00 2E
00053221 FF 00
00053222 FF 00
0005322D 6A B5
0005322E D3 58
0005322F 59 ED
00053230 17 E8
```

0x13 through 0x1B are the optional string that I'm stubbornly refusing to add. :)

0x53221 through 0x53222 is the bcdDevice field of the DFU suffix.  UM0391 says it should be 0xFFFF if not used.

0x5322D through 0x53230 are the CRC-32 at the end of the file.  Since the contents of the file are different, the CRC rightfully should be different.

**Comment by amfern** [comment]
yep, this solved it, Thanks you very much
